repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
  - id: black
    language_version: python3
    args:
    - --target-version=py39
    - --target-version=py310
    - --target-version=py311
    - --target-version=py312

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
  - id: ruff

- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
    language_version: python3

- repo: https://github.com/asottile/pyupgrade
  rev: v3.16.0
  hooks:
  - id: pyupgrade
    args:
    - --py39-plus

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  - id: absolufy-imports

- repo: https://github.com/asottile/yesqa
  rev: v1.5.0
  hooks:
  - id: yesqa

- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    args: [--ignore-missing-imports]
    additional_dependencies:
    - dask
    - types-PyYAML
    - pytest
    - numpy
