name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.8
  - dask
  - aiohttp
  - requests
  - pytest
  - pyarrow
  - pip
  - pip:
    - awkward>=1.10.0
