name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.8
  - dask
  - aiohttp
  - requests
  - pytest
  - pyarrow
  - pip
  - pip:
    - git+https://github.com/scikit-hep/awkward@a2e91db99ed2a012231503584998ead20933393b
