name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.8
  - dask
  - pytest
  - pyarrow
  - pip
  - pip:
    - git+https://github.com/scikit-hep/awkward-1.0
