name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.9
  - dask
  - aiohttp
  - requests
  - pytest
  - pyarrow
  - pip
  - pip:
    - awkward==2.0.0rc2
