name: No awkward

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

concurrency:
  group: 'no-awkward-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: install
      run: |
        pip install pip wheel -U
        pip install -q --no-cache-dir .
        pip uninstall awkward -y
        pip list
    - name: test
      run: |
        python -m pytest tests/test_no_awkward
