name: PyPI Tests

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  pytest:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9"]
    runs-on: ${{matrix.platform}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: install
      run: |
        python -m pip install pip setuptools -U
        python -m pip install wheel -U
        python -m pip install pytest -U
        pip cache purge
        pip install --ignore-installed -q --no-cache-dir git+https://github.com/scikit-hep/awkward-1.0@main -v
        pip install --ignore-installed --no-deps -q --no-cache-dir -e .
        pip list
    - name: test
      run: |
        python -m pytest
