name: Tests

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  pytest:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{matrix.platform}}
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python3 -m pip install pip setuptools wheel
        python3 -m pip install --ignore-installed -U -q --no-cache-dir -e .[complete]
        python3 -m pip list
    - name: Run tests
      run: |
        python3 -m pytest
